### ISSUE TITLE
The spell fields don't line up with their headers

### ISSUE THREAD

**Issue by johnlamping** [epic-power-rpg/roll20#19]
This code shrinks many of the spell fields by one:
.spell-row>input~input,
.spell-row>input~select,
.spell-row>select~input {
  /* Make consecutive buttons overlap */
  margin-left: -1px;
}

But there is nothing comparable for the table headers.
The answer is probably to add a new selector: .input-header, which headers for inputs or select get, and then add
.input-header~.input-header {
  /* Shrink to correspond to the consecutive buttons overlap */
  margin-left: -1px;
}

**Comment by jazeee** [comment]
The margin-left `-1px` makes things complicated.
Instead, I think we should look at other options.
One option is to simply remove them, as seen in #23

**Comment by jazeee** [comment]
I have an alternative - using `display: grid`:
![image](https://user-images.githubusercontent.com/5629800/206948485-a9628098-34c9-4bd6-bfb9-00316d8a9ff4.png)

**Comment by jazeee** [comment]
Example: https://github.com/epic-power-rpg/roll20/pull/24

**Comment by jazeee** [comment]
I believe this issue is now resolved.
