### ISSUE TITLE
Change second column of defenses to be defense without armor

### ISSUE THREAD

**Issue by johnlamping** [epic-power-rpg/roll20#35]
I noticed that you often need to know defense without armor (mostly for armor skirting attacks). On the other hand, defense against ranged attacks is not that useful, because what you usually want is defense vs missile and defense vs beam.

So the character sheet in the rules now shows defense with and without armor. It would be good to update the online character sheet to do the same. That is probably a good task for me (John), to get me familiar with working with all the nice new stuff. But I'm feeling a bit sick right now, so it may be a few days before I get to it.

**Comment by jazeee** [comment]
Nice!

**Comment by jazeee** [comment]
I'll take this on next. Looking at the code, it seems manageable.

**Comment by jazeee** [comment]
One of the oddities, though, is that `parry` is really only applicable to melee.
`Parrying` doesn't make sense for ranged defense, hence, ranged attacks don't  don't have the `parry` input field.

Parry doesn't get used in any calculations. I wonder if it should be extracted out - perhaps similar to defense penalty being separate.

**Comment by jazeee** [comment]
I could see a couple of options:
![image](https://user-images.githubusercontent.com/5629800/212579461-8fb08707-7236-4ae9-9509-b05d32f806df.png)
or merged as a single column:
![image](https://user-images.githubusercontent.com/5629800/212580808-cc5bc69a-286a-482f-a326-bf3942e2088a.png)

@johnlamping - thoughts?

**Comment by johnlamping** [comment]
I think I slightly prefer the two column version. But I think it would be better to have the armor column before the no armor column, because armor is the usual case. So the columns would be something like "Def.", "armor" "w/o armor"

Parry should work just like the other two defenses, now that there is no special case for ranged. The problem is that it needs to know what the parry bonus of your weapon is, and that isn't currently recorded on the character sheet. I can think of a couple of options: Add a new field to weapons, giving their parry bonus; then use the highest bonus as the bonus for parry. Add a new field to the defense block where you can fill in the Parry bonus. I don't see a nice place for it, though.

BTW, it would also be nice if the Block row has "--" values if you had no shield, and if the Parry row had "--" values if you ha no weapon with a parry bonus.

**Comment by johnlamping** [comment]
Maybe the column headers would be better as
So the columns would be better as "Def.", "Ability" "w/o armor"

**Comment by jazeee** [comment]
I'll get something in place to review.
I suspect that the `w/o armor` will word wrap, though.

**Comment by jazeee** [comment]
![image](https://user-images.githubusercontent.com/5629800/212786145-f7259a85-ebc0-45ac-bde3-e2b975a54d9d.png)

**Comment by johnlamping** [comment]
Maybe strikethrough, like armor?

**Comment by jazeee** [comment]
Ohh, that could work. Testing...

**Comment by jazeee** [comment]
![image](https://user-images.githubusercontent.com/5629800/212787853-659ce45c-9302-459c-9b9d-d71c9c5dc91c.png)

**Comment by jazeee** [comment]
Also, tooltip when hovering:
![image](https://user-images.githubusercontent.com/5629800/212787910-60b2de1c-3114-497c-b4d2-422db614366c.png)

**Comment by jazeee** [comment]
Moved the parry topic to https://github.com/epic-power-rpg/roll20/issues/69

**Comment by jazeee** [comment]
> BTW, it would also be nice if the Block row has "--" values if you had no shield,
![image](https://user-images.githubusercontent.com/5629800/212791740-aeee9867-16d7-4a7e-906b-b4bf9c1b04da.png)

In https://github.com/epic-power-rpg/roll20/pull/68
