### ISSUE TITLE
Consider converting to pug templates

### ISSUE THREAD

**Issue by jazeee** [epic-power-rpg/roll20#36]
Compiling HTML and importing other HTML snippets is a bit unwieldy.
Several Roll20 examples use `pug` to template and assemble HTML snippets into character sheets.
[Pug](https://pugjs.org/language/includes.html)

Some example Roll20 Pug usage:
1. https://github.com/Roll20/roll20-character-sheets/blob/master/ADnD_2E_Revised/pug/weaponsOverview.pug
2. https://github.com/Roll20/roll20-character-sheets/blob/master/backbone/source/backbone.pug

@johnlamping thoughts?

**Comment by johnlamping** [comment]
Pug looks like it could make the html a lot more modular.
Would the plan be to first run an html to pug converter, and then
incrementally clean things up?

**Comment by jazeee** [comment]
I'm unsure. I'll push up a PR that test things out.
It looks like we can mix-and-match.

Personally, I prefer plain html, but I'll add an example conversion of one html file.

**Comment by jazeee** [comment]
Here is a first pass:
https://github.com/epic-power-rpg/roll20/pull/37

**Comment by jazeee** [comment]
#39 shows how we could use `pug` to generate html with loops and variables.
It could work well.
