### ISSUE TITLE
The overview tab should only show advantages that the character has taken.

### ISSUE THREAD

**Issue by johnlamping** [epic-power-rpg/roll20#46]
I just noticed that the overview tab is showing all advantages, not just the ones the character has taken. Much as I would like to blame that on the recent changes, I checked back and saw that it was happening on my watch too. I don't know if you can selectively turn off a line of a grid. If not, the fix may be to have a single div that holds everything and is display: content, and has its content selectively displayed.

**Comment by jazeee** [comment]
I think we can do this in similar ways to the weapon notes css.
I'll take a look.

**Comment by jazeee** [comment]
Fixed in #47
