### ISSUE TITLE
Some issues with skill formatting

### ISSUE THREAD

**Issue by johnlamping** [epic-power-rpg/roll20#48]
Spells and skills are not indented under their discipline.  Indenting makes it easier to see that they belong to that discipline. It used to be that they were right justified, which might be the best way to go. That puts the spell name close to all its info.

The Attribute field is stretching. It should be fixed width, since the attribute values can never be very long (just enough to hold "IQ+DX".

For arcane spells, when a line is tagged as a discipline, the name should be bolded, and most of the content of the line should disappear, leaving just the name, TP, and expertise. (Skills work right on this.)

For arcane spells, the only columns that should stretch are name, cast time, target and damage/duration.

(I've put the latest character sheet in the Alanya arc, and I'm recording issues as I note them while setting up NPC.)

**Comment by johnlamping** [comment]
Also, for arcane spells, when a line is tagged as a discipline, the IQ and base should not appear. (Skills work right on this.)

**Comment by johnlamping** [comment]
A thought: Notes for spells might look better as a down arrow, rather than a check box. That would visually indicate the connection between the box and the note.

**Comment by jazeee** [comment]
I'm thinking that the notes could become popovers instead. This would clean
up the table and make them more manageable.

**Comment by johnlamping** [comment]
Oh, right. You had mentioned popovers, and I forgot. That seems like a
better idea.

Given that, I don't see any point in changing the check marks now.

**Comment by johnlamping** [comment]
Another problem: You can't delete a row in the skills if it is a discipline. I have no idea why this would be, since the deletion is under Roll20's control, not the character sheet's. The delete button appears, but nothing happens when you click on it. The delete button does work for arcane spells, though.

I'm guessing that it is some interaction with not showing the attribute and base. They don't appear for skills (where you can't delete) but do currently appear for arcane spells (where you can delete).

**Comment by johnlamping** [comment]
I'm not sure about this one: It is a bit confusing to see how to make popovers go away, because what you have to click on is the question mark, which is not inside the popover. One option would be to make popovers go away whenever you click anywhere else. But then there is no way to see the popover while you work with anything else. Another option would be to give all popovers a close button in the upper right.
If they get a close button, it would be very cool if they could also be dragged around on the window. That way, you could move them out of the way when you want to consult them while you are also doing stuff. I have no idea how hard that is to do, though. I assume it would involve some javascript to intercept the drags, which sounds like a pain.

**Comment by johnlamping** [comment]
For innate spells, the column title should be Damage/Duration, not just Duration.

**Comment by jazeee** [comment]
Moved popover topics to #49

**Comment by jazeee** [comment]
> Another problem: You can't delete a row in the skills if it is a discipline. I have no idea why this would be, since the deletion is under Roll20's control, not the character sheet's. The delete button appears, but nothing happens when you click on it. The delete button does work for arcane spells, though.
> 
> I'm guessing that it is some interaction with not showing the attribute and base. They don't appear for skills (where you can't delete) but do currently appear for arcane spells (where you can delete).

I tested this on all three spell types. From my testing delete works fine, unless the row has no data. This does seem like a Roll20 specific issue.
I am pretty sure this is not a new bug.
Verified on the original sheet in Jazlanya.

**Comment by jazeee** [comment]
Ahh, I see the error. This is related to CSS styling. I am going to refactor this, since it is confusing.
The skills tab at the end of this video:

https://user-images.githubusercontent.com/5629800/211176481-ad27daf7-1c1e-4784-a8fd-96ca6629775d.mp4

Fixed:

https://user-images.githubusercontent.com/5629800/211176758-a699c372-2407-4b73-9287-cab7b4c1e81e.mp4

**Comment by jazeee** [comment]
Also some other style fixes coming:
![image](https://user-images.githubusercontent.com/5629800/211177698-5ed1ad3c-58b1-4abb-87dc-f1c2a76bd700.png)

**Comment by jazeee** [comment]
Ok, I believe I have a bunch of these adjusted on #51
We can also adjust these as needed.
Assuming fonts are consistent and everyone uses the same zoom level, I believe this should work.
