### ISSUE TITLE
The notes fields for spells and elsewhere should expand vertically as necessary.

### ISSUE THREAD

**Issue by johnlamping** [epic-power-rpg/roll20#5]
I think I tried to do this once, and failed. It may be that Roll20 doesn't support this functionality. But maybe there is a way to have two html elements, one that shows only when you are not editing and resizes, and one that shows only when you are editing, and doesn't resize if roll20 doesn't support multi-line editors.

**Comment by jazeee** [comment]
Let me see if I can get this working better.

**Comment by jazeee** [comment]
Notes can be a text area, but I didn't find a way to expand vertically.

Here is an example:
![image](https://user-images.githubusercontent.com/5629800/206938514-99981d88-3f7d-4f46-bc02-8c57dbf0fdb4.png)
