### ISSUE TITLE
Fix defense styles in top section

### ISSUE THREAD

**Issue by jazeee** [epic-power-rpg/roll20#64]
Realign styles in this section:
![image](https://user-images.githubusercontent.com/5629800/212570362-1489dfc7-0736-4087-b35c-b5ae862bb4a9.png)

**Comment by jazeee** [comment]
@johnlamping - I'll be fixing these issues next.

**Comment by johnlamping** [comment]
Great!

(All my time is going to get the next arc ready, so I probably won't be
doing any coding for another couple of months.)

**Comment by jazeee** [comment]
Sounds good. I'll keep pushing PR's for review. 👍🏾
