### ISSUE TITLE
Rework Parry fields

### ISSUE THREAD

**Issue by jazeee** [epic-power-rpg/roll20#69]
The problem is that it needs to know what the parry bonus of your weapon is, and that isn't currently recorded on the character sheet. I can think of a couple of options: 
* Add a new field to weapons, giving their parry bonus; then use the highest bonus as the bonus for parry.
* Add a new field to the defense block where you can fill in the Parry bonus. I don't see a nice place for it, though.

If the Parry row had "--" values if you ha no weapon with a parry bonus.

_Originally posted by @johnlamping in https://github.com/epic-power-rpg/roll20/issues/35#issuecomment-1384362920_

**Comment by johnlamping** [comment]
It would make sense for the new weapon field to be titled "Def.", like the fields for armor and shield. That would make things relatively consistent.
And, with my wishes turning into code so fast, Jaz ... Giving the Def. headers an explanatory popover would be a nice touch. They would say something, "Amount added to all defenses" "Amount added to Block defense", "Amount added to Parry defense", respectively

**Comment by jazeee** [comment]
I'm going to take a look at this now. (sorry about the delay lol)

**Comment by jazeee** [comment]
![image](https://user-images.githubusercontent.com/5629800/213895966-fc7981c1-9449-40cc-b116-24e67f716226.png)
![image](https://user-images.githubusercontent.com/5629800/213896167-db68c1f7-d206-494e-9e19-66aab3ddf056.png)

**Comment by jazeee** [comment]
@johnlamping - is the parry calculated as weapon parry + armor?
In other words, is there parry with armor and parry without armor?

**Comment by johnlamping** [comment]
Yes. The normal calculation is weapon parry + defense ability + armor, and
the no armor calculation is weapon parry + defense ability.
BTW, I'd suggest putting the Def. field first, so it is the first field for
armor, shield, and weapons.

**Comment by jazeee** [comment]
Sure. I was just thinking that the weapon is primarily used for attack, hence damage range def.
Easy enough to move it though.

**Comment by johnlamping** [comment]
Good point. In fact, since you point that out, it seems like Damage and
Range should come first for weapons, followed by Def., then the rest of the
stuff. I must not have been thinking when I put them where they are.

**Comment by jazeee** [comment]
Got the columns in place.
Separately, I'll update the parry section
https://github.com/epic-power-rpg/roll20/pull/70

**Comment by jazeee** [comment]
Ok, got the calculation code working.
PR coming

**Comment by jazeee** [comment]
![image](https://user-images.githubusercontent.com/5629800/213899453-e032ac20-2669-4f68-9468-d7c34236a5f4.png)
![image](https://user-images.githubusercontent.com/5629800/213899458-a3ec23b3-997e-42b7-9067-0e228f456233.png)
